name: Java CI with Maven

on:
  push:
    branches:
      - CA5
  pull_request:
    branches:
      - CA5

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up JDK 19
      uses: actions/setup-java@v3
      with:
        java-version: '19'
        distribution: 'oracle'
        cache: 'maven'

    - name: Run Maven tests
      run: |
        cd CA3/Fesadyab
        mvn test -B -f pom.xml
